name: repo_size
run-name: size_repo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            sparse-checkout: .
      - run: echo
      - run: du -skh --exclude=".git"